export const storeProducts = [
  {
    id: 1,
    title: "IT Luggage The LITE 4 Wheel Soft Cabin Suitcase",
    img: "https://images.unsplash.com/photo-1578950435899-d1c1bf932ab2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGxhcHRvcHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: 29.99,
    company: "IT Luggage",
    info: "Get more done with this high-performance laptop. It's perfect for multitasking and creative work.",
    names: "Apple",
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Go Explore Small 4 Wheel Hard Suitcase",
    img: "https://images.unsplash.com/photo-1602080858428-57174f9431cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGxhcHRvcHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: 16.99,
    company: "Go Explore ",
    info: "This is a powerful laptop with high-end features. It's perfect for gaming and professional work.",
    names: "HP",
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Ionian 8 Wheel Frameless Cabin Case",
    img: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGxhcHRvcHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: 40,
    company: "IT Luggage",
    info: "Experience the latest in laptop technology with this sleek and lightweight device.",
    names: "Dell",
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: " Tourister Soundbox 8 Wheel Spinner 55",
    img: "https://images.unsplash.com/photo-1580522154071-c6ca47a859ad?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxhcHRvcHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: 43,
    company: "American Tourister",
    info: "SoundBox is the first expandable American Tourister zipped PP case. A fixed 3 dial recessed TSA combination lock on all sizes gives maximum security. Made from resistant polypropylene. Elastic cross-ribbons in top and bottom compartment. The combination of the concentric wave design with the fine matt texture creates a playful design.",
    names: "Samsung",
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Bon Air 4 Wheel Spinner",
    img: "https://plus.unsplash.com/premium_photo-1673548917296-e067951dd7de?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bGFwdG9wc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: 50,
    company: "American Tourister",
    info: "offering extra space to storage your belongings.",
    names: "HP",
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "World's Lightest 2 Wheel Cabin Suitcase",
    img: "https://images.unsplash.com/photo-1629131726692-1accd0c53ce0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bGFwdG9wc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: 60,
    company: "IT ",
    info: " This case also features a detachable travel liquids bag inside and comes with a 10 year manufacturer's warranty. Also comes in a medium and large size.",
    names: "Hp",
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Small Expandable 4 Wheel Hard Suitcase",
    img: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGFwdG9wc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: 40,
    company: "apple",
    info: " this small cabin case is hardwearing and versatile: green details on the handle and the suitcase itself mean you'll never lose it on the luggage carousel.",
    names: "Lenovo",
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Asteroid 2 Wheel Hard Cabin Suitcase",
    img: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bGFwdG9wc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: 25,
    company: "Asus",
    info: " The central opening is designed to provide an ideal flat packing surface whilst the expander system gives 25% extra space when you need it most without compromising on the suitcases stability, making this the ideal case for business trips as well as holidays and weekends away.",
    names: false,
    count: 0,
    total: 0,
  },
];
